[colors.primary]
background = '#434c5e'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[cursor.style]
blinking = "On"
shape = "Underline"

[font.normal]
family = "MesloLGS Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_title = false
opacity = 0.7

[window.padding]
x = 5
y = 5
