[colors.primary]
background = '#434c5e'
foreground = '#e5e9f0'

[colors.normal]
black= "#3b4252"
red= "#bf616a"
green= "#a3be8c"
yellow= "#ebcb8b"
blue= "#81a1c1"
magenta= "#b48ead"
cyan= "#88c0d0"
white= "#e5e9f0"

[colors.bright]
black= "#4c566a"
red= "#bf616a"
green= "#a3be8c"
yellow= "#ebcb8b"
blue= "#81a1c1"
magenta= "#b48ead"
cyan= "#8fbcbb"
white= "#eceff4"

[colors.dim]
black= "#373e4d"
red= "#94545d"
green= "#809575"
yellow= "#b29e75"
blue= "#68809a"
magenta= "#8c738c"
cyan= "#6d96a5"
white= "#aeb3bb"

[cursor.style]
blinking = "On"
shape = "Underline"

[font.normal]
family = "MesloLGS Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_title = false
opacity = 0.7

[window.padding]
x = 5
y = 5
